### PR TITLE
added tissue templates

### PR DESCRIPTION
**Pull request by michaeldera**

### CODE REVIEW

**Review by OlivierJM — CHANGES_REQUESTED** [review]
The PR title should be issue right instead of tissue?

**Comment by terrymafura** [comment]
Tissue because it's supposed to wipe all problems, lol

**Comment by michaeldera** [comment]
> The PR title should be issue right instead of tissue?

😂😂😂😂😂😂😂😂 Actually Tissue, there is some context to it. https://twitter.com/Guard_Jere/status/1184469384661819396?s=20

**Comment by OlivierJM** [comment]
> Tissue because it's supposed to wipe all problems, lol

😅 This just made my day guys.

**Review by OlivierJM — APPROVED** [review]
OMG I missed the point 🤦🏾‍♂️😅

**Comment by michaeldera** [comment]
> OMG I missed the point 🤦🏾‍♂️😅

Anyone could have 😂😂😂😂😂😂

**Review by terrymafura — CHANGES_REQUESTED** [review]
there some merge conflicts with the README. That's the only issue on this PR @bzmp125

**Comment by bzmp125** [comment]
> there some merge conflicts with the README. That's the only issue on this PR @bzmp125

Yes, because the initial README.md was readme.md (lowercase). I've sorted it out.

**Comment by bzmp125** [comment]
@all-contributors please add @michaeldera for maintenance, documentation

**Comment by bzmp125** [comment]
How can I resolve this issue? @michaeldera @maffsojah

**Comment by terrymafura** [comment]
> How can I resolve this issue? @michaeldera @maffsojah

Since it's only one commit, that could be a problem. I haven't found any solution yet but what if @michaeldera pulls and PR again.

**Comment by michaeldera** [comment]
> > How can I resolve this issue? @michaeldera @maffsojah
> 
> Since it's only one commit, that could be a problem. I haven't found any solution yet but what if @michaeldera pulls and PR again.

You can edit my files to remove the conflict.

**Comment by terrymafura** [comment]
> > > How can I resolve this issue? @michaeldera @maffsojah
> > 
> > 
> > Since it's only one commit, that could be a problem. I haven't found any solution yet but what if @michaeldera pulls and PR again.
> 
> You can edit my files to remove the conflict.

cool, Bakani has write access

**Comment by bzmp125** [comment]
> > > How can I resolve this issue? @michaeldera @maffsojah
> > 
> > 
> > Since it's only one commit, that could be a problem. I haven't found any solution yet but what if @michaeldera pulls and PR again.
> 
> You can edit my files to remove the conflict.

Done. So, I'll be closing this now.

**Comment by bzmp125** [comment]
We need to apply this energy again when the time comes 😆

**Comment by terrymafura** [comment]
> We need to apply this energy again when the time comes 😆

esp on that other project

**Comment by sabelo-n** [comment]
We need to fix the cowntri most importantly

**Pull request closed without merging**
