### PR TITLE
add bootstrap to index.html

### PR DESCRIPTION
**Pull request by terrymafura**
## Description

Updated `index.html`, added a little bootstrap and switched to one image folder

### CODE REVIEW

**Comment by bzmp125** [comment]
Looks great @maffsojah, maybe we could add more content as we continue. Do you want to spearhead the Road Map discussions for this project?

Merging the PR

**Comment by terrymafura** [comment]
> Looks great @maffsojah, maybe we could add more content as we continue. Do you want to spearhead the Road Map discussions for this project?
> 
> Merging the PR

Yes boss I’d love to, I’ll open up an Issue for that discussion

**Comment by terrymafura** [comment]
In the meantime @bzmp125 add yourself on the contributors list. I couldn’t add you

**Comment by bzmp125** [comment]
> In the meantime @bzmp125 add yourself on the contributors list. I couldn’t add you

haha, ok let me do that.

**Comment by bzmp125** [comment]
@all-contributors please add @bzmp125 for maintenance, financial

**Pull request merged**
